name: finpal
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  # 기본 아이콘
  cupertino_icons: ^1.0.8

  # 상태 관리
  flutter_bloc: ^8.1.4
  equatable: ^2.0.5

  # 함수형 프로그래밍
  dartz: ^0.10.1

  # Firebase
  firebase_core: ^3.7.0
  firebase_auth: ^5.3.2
  cloud_firestore: ^5.4.5
  firebase_storage: ^12.3.5

  # 인증
  google_sign_in: ^6.2.1

  # 유틸리티
  uuid: ^4.5.1
  intl: ^0.19.0
  logger: ^2.1.0
  cached_network_image: ^3.3.1
  image_picker: ^1.0.7
  path_provider: ^2.1.2

  # UI
  flutter_svg: ^2.0.10
  shimmer: ^3.0.0
  lottie: ^3.1.0

  # Google Cloud Vision API
  googleapis: ^13.2.0
  googleapis_auth: ^1.4.1
  http: ^1.2.2
  get_it: ^8.0.2
  fl_chart: ^0.69.0
  go_router: ^14.4.1
  flutter_dotenv: ^5.2.1
  sign_in_with_apple: ^6.1.3
  shared_preferences: ^2.3.3
  image_cropper: ^8.0.2
  flutter_image: ^4.1.11
  image: ^4.3.0
  path: ^1.9.0
  google_generative_ai: ^0.4.6
  kakao_flutter_sdk: ^1.9.6
  kakao_flutter_sdk_auth: ^1.9.6
  kakao_flutter_sdk_user: ^1.9.6
  kakao_flutter_sdk_share: ^1.9.6
  kakao_flutter_sdk_talk: ^1.9.6
  kakao_flutter_sdk_template: ^1.9.6
  kakao_flutter_sdk_friend: ^1.9.6
  kakao_flutter_sdk_navi: ^1.9.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # 테스트
  bloc_test: ^9.1.6
  mockito: ^5.4.4
  build_runner: ^2.4.8
  
  # 린트
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # assets:
  #   - assets/images/
  #   - assets/icons/
  #   - assets/animations/

  # fonts:
  #   - family: Pretendard
  #     fonts:
  #       - asset: assets/fonts/Pretendard-Regular.otf
  #       - asset: assets/fonts/Pretendard-Medium.otf
  #         weight: 500
  #       - asset: assets/fonts/Pretendard-Bold.otf
  #         weight: 700

  assets:
    - .env
    - assets/icons/